name: appy
description: "Appy - Aplicación educativa para autismo"
publish_to: "none" # Para paquetes privados

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

    # ----------------------------
    # Level Timeline Module Assets
    # ----------------------------
    - assets/images/LevelBGs/                     # Carpeta principal de fondos de niveles
    - assets/images/LevelBGs/Higiene/            # Subcarpeta del módulo Higiene
    - assets/images/LevelBGs/Higiene/StepsBGs/   # Fondos específicos de pasos del módulo Higiene

    # ----------------------------
    # Avatar Skins Module Assets
    # ----------------------------
    - assets/images/Skins/                                   # Carpeta principal de skins
    - assets/images/Skins/accesorios generales/             # Accesorios desbloqueables generales
    - assets/images/Skins/DefaultSkin/                      # Skin por defecto
    - assets/images/Skins/DefaultSkin/backgrounds/          # Fondos para la skin por defecto
    - assets/images/Skins/DefaultSkin/expresions/           # Expresiones para la skin por defecto

    - assets/images/Skins/Astronaut/                        # Skin Astronauta
    - assets/images/Skins/Astronaut/backgrounds/           # Fondos de Astronauta
    - assets/images/Skins/Astronaut/expresions/            # Expresiones de Astronauta

    - assets/images/Skins/Chef/                             # Skin Chef
    - assets/images/Skins/Chef/backgrounds/                # Fondos de Chef
    - assets/images/Skins/Chef/expresions/                 # Expresiones de Chef

    - assets/images/Skins/Dinosaur/                         # Skin Dinosaurio
    - assets/images/Skins/Dinosaur/backgrounds/            # Fondos de Dinosaurio

    - assets/images/Skins/Firefighter/                      # Skin Bombero
    - assets/images/Skins/Firefighter/backgrounds/         # Fondos de Bombero

    - assets/images/Skins/Superhero/                        # Skin Superhéroe
    - assets/images/Skins/Superhero/backgrounds/           # Fondos de Superhéroe
